### ISSUE TITLE
Please allowlist exposure-notifications-verification-server project to use mako.dev

### ISSUE THREAD

**Issue by p3y1c2n** [google/mako#14]
Hi Mako folks, 

Cloud you please add [exposure-notifications-verification-server](https://github.com/google/exposure-notifications-verification-server) project to the allowlist? We are planing to use mako for performance testing.

Thanks!

**Comment by timford** [comment]
Hello! Please have a Googler reach out to us at http://go/mako#gaining-access to set this up. Thanks!
