### ISSUE TITLE
Compiled proto and gRPC files in the repo

### ISSUE THREAD

**Issue by PeterZhizhin** [google/mako#4]
It appears that some files in this repo are compiled .proto files.

For example:
https://github.com/google/mako/blob/master/internal/quickstore_microservice/proto/quickstore_go_proto/quickstore.pb.go
https://github.com/google/mako/blob/master/internal/quickstore_microservice/proto/quickstore_go_grpc_pb/quickstore.pb.go

Can you provide context on why you have compiled protos here? Bazel should be able to generate these from .proto definitions, right?..

**Comment by timford** [comment]
Hi Peter! The explanation for that is that our existing customers use `go build/test` rather than Bazel. For that reason, the proto Go code must be pregenerated and checked in. When using Bazel these files are ignored.
