### ISSUE TITLE
Use klog instead of glog

### ISSUE THREAD

**Issue by coryrc** [google/mako#6]
https://github.com/kubernetes/klog

Reasons why are on the page and copied below.

Besides replacing the three import uses and change glog->klog, a call to klog.InitFlags(nil) must also be made; at package initialization time is just fine.

The bad design of glog makes it hard to interact with other systems.

The decision to create klog was one that wasn't made lightly, but it was necessary due to some drawbacks that are present in glog. Ultimately, the fork was created due to glog not being under active development.

glog presents a lot "gotchas" and introduces challenges in containerized environments, all of which aren't well documented.
glog doesn't provide an easy way to test logs, which detracts from the stability of software using it

**Comment by timford** [comment]
Thanks for the report @coryrc . Can you give us an idea how this broke your tests?

**Comment by coryrc** [comment]
If klog.InitFlags(nil) is called when glog is included, it will try to define an existing flag. Our presubmit tests do not use the full Mako, so it didn't fail until after checkin.
