### ISSUE TITLE
Please whitelist Asylo project to use Mako

### ISSUE THREAD

**Issue by lbaraz** [google/mako#8]
The project is github.com/google/asylo

Is it OK to post owners here ?

Thanks!

**Comment by timford** [comment]
Project should be ready to go, with details in email.

**Comment by lbaraz** [comment]
Sorry, I still get the same error message:

% mako create_benchmark
third_party/asylo/platform/primitives/perf/mako.config
***
 User 'asylo-guitar@prod.google.com' is not whitelisted to be added as an
owner. See https://github.com/google/mako/blob/master/docs/ACCESS.md for
more information.
***

*Leonid Baraz*

SW Engineer

lbaraz@google.com

US-KIR-6THC-1
<https://campusmaps.googleplex.com/?q=location_id:US-KIR-6THC-1-192E>
