### ISSUE TITLE
Please whitelist agones.dev project to use mako.dev

### ISSUE THREAD

**Issue by aLekSer** [google/mako#9]
We are willing to use mako.dev for performance benchmarks.

The project repo:
https://github.com/googleforgames/agones

Note that while doing:
`mako create_benchmark`

I receive such an error:
```
 permission denied to write: caller alexander.apalikov@globant.com must be whitelisted. Contact perfgate-eng@google.com to request to be added.
```

**Comment by timford** [comment]
Hi aLekSer. Thanks for your interest.

At this time, Mako requires a Google employee with an @google.com address to set up a Mako project. If your project is associated with Google (it appears to me to be), please have an associate who works at Google reach out to us and we can provide further instruction for getting set up with Mako.

**Comment by thisisnotapril** [comment]
Hi @timford I'll send over an email!

**Comment by markmandel** [comment]
Gentle bump - did this get resolved? @thisisnotapril @timford ?

**Comment by timford** [comment]
This was resolved internally.
